name: PR against main CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run Test
      run: make test

    - name: Build application
      run: make build